ref_38: 
  fasta: "/home/cuong.pham/Reference.Broad-resourcebundle_GRCh38/Homo_sapiens_assembly38.fasta"
  interval_list: "resource/preprocessed_intervals.interval_list"
  primary_contigs_fai: "/home/cuong.pham/Exec/sv_workflow/resources/v1/contig.fai"
  primary_contigs_list: "/home/cuong.pham/Exec/sv_workflow/resources/v1/primary_contigs.list"
  inclusion_bed: "resource/hg38_primary_contigs.bed"
  genome_file: "resource/hg38.genome"
  mei_bed: "resource/GatherBatchEvidence/mei_hg38.bed.gz"
  cytoband: "resource/GatherBatchEvidence/cytobands_hg38.bed.gz"
  exclude_intervals_cnv : "resource/hg38.wgs.blacklist.wPAR.bed"
  contig_ploidy_priors: "/home/cuong.pham/Exec/sv_workflow/genomAD_sv_pipeline/resource/hg38.contig_ploidy_priors_homo_sapiens.tsv"
  copy_number_autosomal_contigs: 2
  manta_region: "/home/cuong.pham/Exec/gatk_sv_snakemake/resource/primary_contigs_plus_mito.bed.gz"
  segdup: "resource/hg38.SD_gaps_Cen_Tel_Heter_Satellite_lumpy.blacklist.sorted.merged.bed.gz"
  rmsk: "resource/hg38.randomForest_blacklist.withRepMask.bed.gz"
  pesr_exclude: "resource/PESR.encode.peri_all.repeats.delly.hg38.blacklist.bed.gz"
  bin_exclude: "resource/bin_exclude.hg38.gatkcov.bed.gz"
  seed_cutoff: "resource/seed_cutoff.txt"
  sd_loc: "resource/Homo_sapiens_assembly38.dbsnp138.vcf"